spring.application.name=study-spring

# H2 파일 DB (embedded 모드)
spring.datasource.url=jdbc:h2:file:/workspaces/Spring_Study/study-spring/data/test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 스프링 부트 내장 H2 웹 콘솔 켜기
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Codespaces 리다이렉트 설정
server.forward-headers-strategy=framework